apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: three-tier
  name: mongo-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/filesystem/home/ubuntu/data/db
