apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: three-tier
  name: mongo-pvc
spec:
  volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Ensure this matches your PV capacity
  storageClassName: manual  # Same as the storageClassName in PV
