apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: three-tier
  name: mongo-volume-claim
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
