apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort # This allows external access, can also be NodePort if LoadBalancer is not available
