apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tanzeelkz/mern-frontend:11 # Replace with actual image name or use a build process
          ports:
            - containerPort: 5173
          env:
            - name: REACT_APP_API_URL
              value: "http://backend:5050"
