apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
  labels:
    role: backend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tanzeelkz/mern-backend:{{ .Values.image.tag } # Replace with the actual backend image name
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_CONN_STR
          value: mongodb://mongo:27017/mydatabase
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: password
