apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP  # Internal access within the cluster
