name: ci mern stack frontend application 

on:
  push:
    branches:
       - main
    paths:
       - helm/frontend-charts/**
       - Kubernetes-Manifests-file/frontend/**
       - README.md
       - Application-Code/frontend/**
       - .github/workflows/Frontend-CI.yml

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
          fetch-depth: 0
      
    # Trivy Filesystem Scan
  TrivyFs:
     runs-on: ubuntu-latest
     needs: clone
     steps:

     - name: Checkout code
       uses: actions/checkout@v4
       with: 
          fetch-depth: 0
     - name: Run Trivy vulnerability scanner in fs mode
       uses: aquasecurity/trivy-action@0.28.0
       with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivyfile.yaml
        
     # Setup sonar-scannar
  code-quality:
    runs-on: ubuntu-latest
    needs: TrivyFs

    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with: 
            fetch-depth: 0
     - name: Setup SonarQube
       uses: warchant/setup-sonar-scanner@v8
        
     - name: Analyze with SonarCloud
       uses: sonarsource/sonarcloud-github-action@master
       env:
          GITHUB_TOKEN: ${{ secrets.Mern_Token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       with:
        args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=Application/frontend/**
            -Dsonar.verbose=true
            
  Build-Push:
     runs-on: ubuntu-latest
     needs: code-quality

     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with: 
          fetch-depth: 0
 

    # Log in to Docker Hub
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Login to DockerHub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and Push action
       uses: docker/build-push-action@v6
       with:
        context: ./Application-Code/frontend
        file: ./Application-Code/frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mern-frontend:${{github.run_id}}
  
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    
    needs: Build-Push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.Mern_Token }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/frontend-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "tanzeelkx@gmail.com"
        git config --global user.name "Tanzeelkz"
        git add helm/frontend-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push origin main
