name: CI for MERN Stack Frontend Application

on:
  push:
    branches:
      - main
    paths: 
      - helm/frontend-charts/**
      - Kubernetes-Manifests-file/frontend/**
      - README.md
      - Application-Code/frontend/**
      - .github/workflows/Frontend-CI.yml

jobs:
  # Step 1: Clone the repository
  build:
    runs-on: self-hosted
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Application-Code/frontend
          file: ./Application-Code/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-frontend:${{ github.run_id }}

      - name: Trivy FS scan
        run: |
         trivy fs --format table -o fs.html .

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TKN}
         SONAR_HOST_URL: ${{ secrets.SONAR_URL}}
