name: CI for MERN Stack Frontend Application

on:
  push:
    branches:
      - main
    paths:
      - helm/frontend-charts/**
      - Kubernetes-Manifests-file/frontend/**
      - README.md
      - Application-Code/frontend/**
      - .github/workflows/Frontend-CI.yml

jobs:
  # Step 1: Clone the repository
  clone:
    runs-on: self-hosted
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Application-Code/frontend
          file: ./Application-Code/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-frontend:${{ github.run_id }}

  

  # Step 6: Update Helm Chart with New Tag
      - name: update-newtag-in-helm-chart
        with:
          fetch-depth: 0
          token: ${{ secrets.Mern_Token }}

      # Update the tag in Helm chart
      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/frontend-charts/values.yaml

      # Commit and push changes to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.email "tanzeelkx@gmail.com"
          git config --global user.name "Tanzeelkz"
          git add helm/frontend-charts/values.yaml
          git commit -m "Update tag in Helm chart"
          git pull --rebase
          git push origin main
