name: CI for MERN stack Frontend Application

on:
  push:
    branches:
      - main
    paths: 
      - Application-Code/frontend/**
      - .github/workflows/Frontend-CI.yml

jobs:
  # Step 1: Clone the repository
  build:
    runs-on: self-hosted
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          
      # Trivy Filesystem Scan
      - name: Trivy FS scan
        run: |
         trivy fs --format table -o fs.html .
         
      # Sonnarqube Code Quality Scan     
      - uses: sonarsource/sonarqube-scan-action@master
        with: 
          projectBaseDir: Application-Code/frontend
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TKN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Application-Code/frontend
          file: ./Application-Code/frontend/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME }}/mern-frontend:${{ github.run_id }}
     
      # Trivy Image Scanner 
      - name: Trivy Image Scan
        run: |
         trivy image --format table -o trivy-image-report.html ${{secrets.DOCKER_USERNAME }}/mern-frontend:${{ github.run_id }}

     
